### PR TITLE
Security Update (PDO Prepare) and Structure Update (move db file)

### PR DESCRIPTION
**Pull request by Rheydskey**
I have change query for PDO prepare to improve security of SQL queries and move db file to a folder lib

### CODE REVIEW

**Comment by Rix565** [comment]
Hello !
A new update is comming. Please wait !

**Comment by Rheydskey** [comment]
Okay

**Comment by Rix565** [comment]
Please help me !
More info in the master branch !
If you want & can to help me , go to the help-me branch !!!!

**Comment by Rix565** [comment]
But...You speak french ???!!!!
Moi aussi, je parle français !

**Comment by Rix565** [comment]
;)

**Comment by Rheydskey** [comment]
Ah bah oui mais Github est un site anglais

**Comment by Rix565** [comment]
###  _FORCÉMENT_

**Pull request closed without merging**
